App\Entity\User:
  properties:
    numOfConfirmedAdults:
      - NotBlank: { message: "Campo obbligatorio", groups: [user_rsvp] }
    numOfConfirmedChildren03:
      - NotBlank: { message: "Campo obbligatorio", groups: [user_rsvp] }
    numOfConfirmedChildren49:
      - NotBlank: { message: "Campo obbligatorio", groups: [user_rsvp] }
    numOfConfirmedVegans:
      - NotBlank: { message: "Campo obbligatorio", groups: [user_rsvp] }
    numOfConfirmedVegetarians:
      - NotBlank: { message: "Campo obbligatorio", groups: [user_rsvp] }
    numOfConfirmedCeliacs:
      - NotBlank: { message: "Campo obbligatorio", groups: [user_rsvp] }
    notes:
      - Length: { maxMessage: "Il campo può contenere massimo 1000 caratteri", max: 1000, groups: [user_rsvp] }