<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHX9xEh2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHX9xEh2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHX9xEh2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHX9xEh2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHX9xEh2\App_KernelDevDebugContainer([
    'container.build_hash' => 'HX9xEh2',
    'container.build_id' => '3b373e54',
    'container.build_time' => 1759268447,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHX9xEh2');
