<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'homepage' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], [], []],
    'homepage_with_section' => [['section'], ['_controller' => 'App\\Controller\\DefaultController::indexWithSection'], [], [['variable', '/', '[^/]++', 'section', true], ['text', '/home']], [], [], []],
    'jewels' => [[], ['_controller' => 'App\\Controller\\DefaultController::jewels'], [], [['text', '/gioielli']], [], [], []],
    'who' => [[], ['_controller' => 'App\\Controller\\DefaultController::who'], [], [['text', '/chi-siamo']], [], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\DefaultController::contact'], [], [['text', '/contatti']], [], [], []],
    'privacy' => [[], ['_controller' => 'App\\Controller\\DefaultController::privacy'], [], [['text', '/privacy-policy']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_font' => [['fontName'], ['_controller' => 'web_profiler.controller.profiler::fontAction'], [], [['text', '.woff2'], ['variable', '/', '[^/\\.]++', 'fontName', true], ['text', '/_profiler/font']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'App\Controller\DefaultController::index' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\DefaultController::indexWithSection' => [['section'], ['_controller' => 'App\\Controller\\DefaultController::indexWithSection'], [], [['variable', '/', '[^/]++', 'section', true], ['text', '/home']], [], [], []],
    'App\Controller\DefaultController::jewels' => [[], ['_controller' => 'App\\Controller\\DefaultController::jewels'], [], [['text', '/gioielli']], [], [], []],
    'App\Controller\DefaultController::who' => [[], ['_controller' => 'App\\Controller\\DefaultController::who'], [], [['text', '/chi-siamo']], [], [], []],
    'App\Controller\DefaultController::contact' => [[], ['_controller' => 'App\\Controller\\DefaultController::contact'], [], [['text', '/contatti']], [], [], []],
    'App\Controller\DefaultController::privacy' => [[], ['_controller' => 'App\\Controller\\DefaultController::privacy'], [], [['text', '/privacy-policy']], [], [], []],
];
